<a id=0></a>  
# 1. Numpy ndarrayを理解する
### ※ Numpy : ”Numerical Python”、数値計算・配列計算を高速で実行できるパッケージ

---
### [1.Python ListとNumpy ndarray ](#1)
### [2.Numpyの関数で連番、等差数列を作成](#2)
### [3.Randomモジュールによる乱数Arrayの作成と次元の変換](#3)
### [4.Numpy ndarrayの次元、形状、サイズ](#4)
### [5.Numpy ndarrayの演算例](#5)
---

Numpyをnpというエイリアス（別名）でインポートする  

In [2]:
import numpy as np

---
<a id=1></a>
[Topへ](#0)

---
## 1.Python ListとNumpy ndarray      

* ListとNumpy ndarrayを作成
* 型（タイプ）を確認  
* Numpy ndarrayのデータタイプ（Numpy ndarrayではすべての要素のデータタイプが統一される）
* Numpy ndarrayの演算例
* Numpy ndarrayの最大値、最小値、平均、合計
* Numpy ndarrayは要素の形状を一定に
* Numpy ndarrayのデータタイプ変換
---

List と ndarrayを作成

In [3]:
arr1 = [1, 3, 5]
arr2 = [2, 4, 6]
arr1

[1, 3, 5]

型（タイプ）を確認  
※ ndarray : n dimentional array（多次元配列）

In [4]:
np_arr1 = np.array(arr1)
np_arr2= np.array(arr2)
np_arr1

array([1, 3, 5])

Numpy ndarrayのデータタイプ（Numpy ndarrayではすべての要素のデータタイプが統一される）

In [5]:
print(type(arr1))
print(type(np_arr1))

<class 'list'>
<class 'numpy.ndarray'>


NumpyArrayの演算例

In [6]:
np_arr1.dtype

dtype('int64')

In [7]:
# arr1.dtype

Numpy ndarrayの最大値、最小値、平均、合計、分散、標準偏差（全要素に対する）

In [8]:
np_arr1 * 2

array([ 2,  6, 10])

In [11]:
np_arr1 + np_arr2

array([ 3,  7, 11])

In [12]:
np_arr1 * np_arr2

array([ 2, 12, 30])

In [ ]:
# arr1 * arr2

In [13]:
np_arr1.max()

5

In [14]:
np_arr1.min()

1

In [18]:
np_arr1.sum()

9

In [19]:
np_arr1.var()

2.6666666666666665

In [20]:
np_arr1.std()

1.632993161855452

ファンシーインデックス

In [24]:
arr3 = [[0, 100], [200, 300]]
np_arr3 = np.array(arr3)

Numpy ndarrayは各次元の要素の形状を一定に

In [25]:
arr3[0][1]

100

In [26]:
np_arr3[0][1]

100

In [27]:
np_arr3

array([[  0, 100],
       [200, 300]])

In [29]:
arr4 = [0, [100, 200], [300, 400, 500]]

In [31]:
arr5=[[0, [1, 2]], [3, [4, 5]]]
np.array(arr5 ,dtype="object")

array([[0, list([1, 2])],
       [3, list([4, 5])]], dtype=object)

Numpy ndarrayのデータタイプ変換

In [33]:
arr6 = [[0, 1, 2.0], [3, 4, 5]]
np_arr6 = np.array(arr6)
np_arr6

array([[0., 1., 2.],
       [3., 4., 5.]])

In [34]:
np_arr6.dtype

dtype('float64')

In [35]:
np_arr6 = np_arr6.astype(int)

In [38]:
np_arr6.dtype

dtype('int64')

In [39]:
arr7 = [[0, 1, "2"], [3, 4, 5]]
np_arr7 = np.array(arr7)
np_arr7.dtype

dtype('<U21')

In [40]:
np_arr7.astype(int).dtype

dtype('int64')

In [41]:
np_arr7.astype(object).dtype

dtype('O')

---
<a id=2></a>
[Topへ](#0)

---
## 2.Numpyの関数で数列を作成

* np.arange(start, stop, step) : 等差数列
* np.linspace(start, stop, size) : 範囲と生成数から作成
---

np.arange(start, stop, step) : 等差数列（正の値のみ）

In [42]:
np.arange(8)
# start = 0, step  = 1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [43]:
np.arange(0, 8, 1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [44]:
np.arange(-5, 5, 1)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

np.linspace(start, stop, size) : 範囲と生成数から作成

In [46]:
np.linspace(0, 8)

array([0.        , 0.16326531, 0.32653061, 0.48979592, 0.65306122,
       0.81632653, 0.97959184, 1.14285714, 1.30612245, 1.46938776,
       1.63265306, 1.79591837, 1.95918367, 2.12244898, 2.28571429,
       2.44897959, 2.6122449 , 2.7755102 , 2.93877551, 3.10204082,
       3.26530612, 3.42857143, 3.59183673, 3.75510204, 3.91836735,
       4.08163265, 4.24489796, 4.40816327, 4.57142857, 4.73469388,
       4.89795918, 5.06122449, 5.2244898 , 5.3877551 , 5.55102041,
       5.71428571, 5.87755102, 6.04081633, 6.20408163, 6.36734694,
       6.53061224, 6.69387755, 6.85714286, 7.02040816, 7.18367347,
       7.34693878, 7.51020408, 7.67346939, 7.83673469, 8.        ])

In [49]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
np.linspace(0, 10, 10, False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

---
<a id=3></a>
[Topへ](#0)

---
## 3.Randomモジュールによる乱数Arrayの作成

* np.random.randint(low, high, size): 整数
* 乱数シード
* np.random.rand(size) : 0以上1未満 
* np.random.randn(size) : 平均0、標準偏差1、正規分布に近づく数列  
* np.random.normal(average, satandard_deviation, size) : 平均と標準偏差を指定、正規分布に近づく数列
* np.random.uniform(low, high, size) : 範囲と生成数を指定
* np.random.choice(array, size) : Listの値をランダムに選択
---

np.random.randint(low, high, size): 整数

In [53]:
np.random.randint(10, 20)

10

In [57]:
np.random.randint(10, 20, 5)

array([10, 18, 15, 11, 19])

In [58]:
np.random.randint(10, 20, (3, 4))

array([[17, 18, 12, 10],
       [17, 11, 16, 15],
       [13, 12, 18, 18]])

In [60]:
np.random.randint(10, 20, (3,4,2))

array([[[17, 16],
        [12, 13],
        [17, 16],
        [18, 14]],

       [[18, 11],
        [12, 15],
        [13, 14],
        [12, 19]],

       [[11, 12],
        [16, 19],
        [16, 17],
        [14, 14]]])

乱数シード

In [63]:
np.random.seed(17)
np.random.randint(1, 100)

16

np.random.rand(size) : 0以上1未満

In [67]:
np.random.randint(1, 100)

46

In [68]:
np.random.rand(5)

array([0.78698546, 0.65633352, 0.6375209 , 0.57560289, 0.03906292])

array([4.14688163, 7.67409912, 2.36026808, 7.18425262, 7.26374316,
       2.30716199, 5.91451169, 5.31050821, 5.58507952, 4.90117175,
       3.69792897, 3.78635431, 5.36905343, 4.37628462, 6.73220426,
       4.51090631, 2.86342352, 2.90544017, 2.3314481 , 6.30822316,
       3.75390413, 3.19264323, 6.98818353, 5.40794672, 2.4940385 ,
       5.26999144, 2.95375247, 6.06057431, 2.71083359, 4.6699764 ,
       7.3278946 , 6.78360638, 2.40787237, 7.76472654, 5.95523235,
       6.3126565 , 6.46146059, 7.32641811, 2.80367401, 6.66184748,
       7.02794907, 6.97582858, 2.17494198, 4.34224695, 4.62351195,
       5.12381038, 4.95723604, 2.78257569, 7.90630119, 2.39421393,
       5.47570447, 5.48464895, 7.72602719, 3.18466267, 2.4999524 ,
       7.30318531, 2.09417716, 6.77356788, 6.60914264, 7.23226272,
       7.49666052, 3.64287916, 3.41828676, 3.86311906, 6.29385955,
       2.49641294, 6.05291866, 7.15114801, 6.1573813 , 6.71050215,
       4.11968751, 3.32115241, 3.47223434, 6.36447509, 2.38476

np.random.randn(size) : 平均0、標準偏差1、正規分布に近づく数列  

    ※ 分散    ：「各数値の平均との差」を平方（2乗）した値の平均（平方するのはプラスの値で測るため）  
    ※ 標準偏差：平均からのばらつき具合を示す指標。分散の正の平方根  
    ※ 正規分布：平均値の度数を中心に、正負の値の度数が同程度に広がる分布      

 np.random.normal(average, satandard_deviation, size) : 平均と標準偏差を指定、正規分布に近づく数列

np.random.uniform(low, high, size) : 範囲と生成数を指定

In [70]:
np.random.uniform(2, 8 , 100)

array([7.38372365, 4.95861403, 5.02686511, 4.1907419 , 6.69803673,
       7.68753812, 2.78009008, 5.96667604, 2.98239385, 3.85363259,
       7.79978093, 4.89712805, 5.24448467, 6.26703881, 6.12459046,
       2.22181489, 7.3290234 , 3.13150525, 6.69216655, 5.86355673,
       4.91239392, 7.57426967, 3.61928848, 6.88507392, 6.17025244,
       3.41318715, 7.71981615, 5.51261425, 5.49839881, 2.94325725,
       4.55144278, 3.41013149, 5.60304396, 4.16365054, 3.01324069,
       4.08347869, 3.28710212, 6.76716976, 6.75025591, 2.98724214,
       6.50218429, 2.33537971, 3.39482255, 5.90057859, 6.30945058,
       4.88029678, 4.02568801, 4.33823774, 7.15278316, 5.06831367,
       7.24814009, 7.67863132, 7.61440227, 4.95822759, 5.60310965,
       3.2430206 , 7.73712963, 7.92086276, 6.97627306, 5.22733676,
       2.50122572, 3.88332493, 2.6366807 , 3.22945187, 3.95311038,
       5.00965392, 7.26991252, 3.56605366, 5.18082064, 7.06317585,
       2.81938692, 4.40134406, 5.41091172, 3.11624728, 2.08229

In [79]:
np.random.uniform(2, 8 , 10000).mean()

4.99669888233691

np.random.choice(array, size) : Listの値をランダムに選択

In [83]:
l = [16, 87, 233]
np.random.choice(l, (2, 3))

array([[ 87,  87, 233],
       [233,  87,  87]])

---
<a id=4></a>
[Topへ](#0)

---
## 4.Numpy ndarrayの次元、形状、サイズ

* 次元
* 形状
* サイズ（要素数）
* 形状の変換 
---

次元

形状

サイズ（要素数）

形状の変換

---
<a id=5></a>
[Topへ](#0)

---
## 5.Numpy ndarrayの演算例

---
[Topへ](#0)

---
## 以上
    
---