---
# DataFrame  Exercise
---

In [95]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Exercise_1 : Pandas の date_range を用いて 2000/7/1 から100日の DatetimeIndexと、2000/7/1 0時からから3時間毎の100個の DatetimeIndexを作成してください（date）

In [96]:
dates = pd.date_range("2000/7/1", periods=100, freq="D")

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>dates = pd.date_range('2000/7/1', periods=100, freq='D')</code>
</details>

In [97]:
# 実行して表示
dates[:10]

DatetimeIndex(['2000-07-01', '2000-07-02', '2000-07-03', '2000-07-04',
               '2000-07-05', '2000-07-06', '2000-07-07', '2000-07-08',
               '2000-07-09', '2000-07-10'],
              dtype='datetime64[ns]', freq='D')

In [98]:
times = pd.date_range("2000/7/1", periods=100, freq="3H")

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>dates = pd.date_range('2000/7/1', periods=100, freq='3H')</code>
</details>

In [99]:
# 実行して表示
times[:10]

DatetimeIndex(['2000-07-01 00:00:00', '2000-07-01 03:00:00',
               '2000-07-01 06:00:00', '2000-07-01 09:00:00',
               '2000-07-01 12:00:00', '2000-07-01 15:00:00',
               '2000-07-01 18:00:00', '2000-07-01 21:00:00',
               '2000-07-02 00:00:00', '2000-07-02 03:00:00'],
              dtype='datetime64[ns]', freq='3H')

Exercise_2 : arr_int と arr_uni の Numpy Array を index方向（縦、1次元方向）、column方向（横、2次元方向）に結合してください（arr_concat_v, arr_concat_h）

In [100]:
# 実行のみ
arr_int = np.random.randint(0, 100, (4, 3))
arr_uni = np.random.uniform(40, 60, (4, 3))

In [101]:
arr_concat_v = np.concatenate([arr_int, arr_uni])
arr_concat_v

array([[34.        , 35.        , 78.        ],
       [45.        , 35.        ,  9.        ],
       [24.        , 26.        , 12.        ],
       [29.        , 33.        , 13.        ],
       [50.46629378, 45.05617439, 52.70728211],
       [54.43863826, 49.11175224, 40.5884552 ],
       [42.88945961, 40.68604438, 54.39768435],
       [42.71480746, 53.92405651, 59.24115031]])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr_concat_v = np.concatenate([arr_int, arr_uni], axis=0)</code>
</details>

In [102]:
# 実行して表示
arr_concat_v.shape
# (8, 3)が表示されればOK

(8, 3)

In [103]:
arr_concat_h = np.concatenate([arr_int, arr_uni], axis=1)
arr_concat_h

array([[34.        , 35.        , 78.        , 50.46629378, 45.05617439,
        52.70728211],
       [45.        , 35.        ,  9.        , 54.43863826, 49.11175224,
        40.5884552 ],
       [24.        , 26.        , 12.        , 42.88945961, 40.68604438,
        54.39768435],
       [29.        , 33.        , 13.        , 42.71480746, 53.92405651,
        59.24115031]])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr_concat_h = np.concatenate([arr_int, arr_uni], axis=1)</code>
</details>

In [104]:
arr_concat_h.shape
# (4, 6)が表示されればOK

(4, 6)

Exercise_3 : arr_concat_v から、Seriesを作成してください（sr1）。　ヒント　次元の変更

In [105]:
sr1 = pd.Series(arr_concat_v.flatten())

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>sr1 = pd.Series(arr_concat_v.flatten())</code>
</details>

In [106]:
# 実行して表示
sr1

0     34.000000
1     35.000000
2     78.000000
3     45.000000
4     35.000000
5      9.000000
6     24.000000
7     26.000000
8     12.000000
9     29.000000
10    33.000000
11    13.000000
12    50.466294
13    45.056174
14    52.707282
15    54.438638
16    49.111752
17    40.588455
18    42.889460
19    40.686044
20    54.397684
21    42.714807
22    53.924057
23    59.241150
dtype: float64

Exercise_4 : arr_concat_h から、indexラベルを ['Zero', 'One', 'Two', 'Three']、columnラベルを ['A', 'B', 'C', 'D', 'E', 'F'] としてデータフレームを作成してください（df1)

In [107]:
df1 = pd.DataFrame(
    arr_concat_h,
    index=["Zero", "One", "Two", "Three"],
    columns=["A", "B", "C", "D", "E", "F"],
)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df1 = pd.DataFrame(arr_concat_h, index=['Zero', 'One', 'Two', 'Three'], columns= ['A', 'B', 'C', 'D', 'E', 'F'])</code>
</details>

In [108]:
# 実行して表示
df1

A     B     C          D          E          F
Zero   34.0  35.0  78.0  50.466294  45.056174  52.707282
One    45.0  35.0   9.0  54.438638  49.111752  40.588455
Two    24.0  26.0  12.0  42.889460  40.686044  54.397684
Three  29.0  33.0  13.0  42.714807  53.924057  59.241150

Exercise_5 : 上記 df の indexラベルを ['P', 'Q', 'R', 'S']、columnラベルを ['col_0', 'col_1', 'col_2', 'col_3', 'col_4', 'col_5'] へ変更してください

In [116]:
new_index = ["P", "Q", "R", "S"]
new_columns = ["col_0", "col_1", "col_2", "col_3", "col_4", "col_5"]
index_corr = {old: new for old, new in zip(df1.index, new_index)}
columns_corr = {old: new for old, new in zip(df1.columns, new_columns)}
# df1 = df1.set_axis(labels=['P', 'Q', 'R', 'S'])
# df1 = df1.set_axis(labels=['col_0', 'col_1', 'col_2', 'col_3', 'col_4', 'col_5'], axis=1)

df1 = df1.rename(index=index_corr, columns=columns_corr)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df1.index = ['P', 'Q', 'R', 'S']</code><br>
    <code>df1.columns = ['col_0', 'col_1', 'col_2', 'col_3', 'col_4', 'col_5']</code><br>
    <code>df1.rename(index={'旧':'新', ...}, columns={'旧':'新', ...})でも可</code>
</details>

In [117]:
# 実行して表示
df1

col_0  col_1  col_2      col_3      col_4      col_5
P   34.0   35.0   78.0  50.466294  45.056174  52.707282
Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
R   24.0   26.0   12.0  42.889460  40.686044  54.397684
S   29.0   33.0   13.0  42.714807  53.924057  59.241150

Exercise_6: 下記 df2 を df1 と index方向へ結合してください（df）。また、column方向へ結合した場合も確認してください（実行するだけです）。

In [118]:
# 実行して表示
arr = np.array(np.arange(24)).reshape(4, 6)
df2 = pd.DataFrame(
    arr,
    index=list("ABCD"),
    columns=["col_0", "col_1", "col_2", "col_3", "col_4", "col_5"],
)  # column名は同じ
df2

col_0  col_1  col_2  col_3  col_4  col_5
A      0      1      2      3      4      5
B      6      7      8      9     10     11
C     12     13     14     15     16     17
D     18     19     20     21     22     23

In [119]:
df = pd.concat([df1, df2], axis=0)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df = pd.concat([df1, df2], axis=0)</code>
</details>

In [120]:
# 実行して表示
df

col_0  col_1  col_2      col_3      col_4      col_5
P   34.0   35.0   78.0  50.466294  45.056174  52.707282
Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
R   24.0   26.0   12.0  42.889460  40.686044  54.397684
S   29.0   33.0   13.0  42.714807  53.924057  59.241150
A    0.0    1.0    2.0   3.000000   4.000000   5.000000
B    6.0    7.0    8.0   9.000000  10.000000  11.000000
C   12.0   13.0   14.0  15.000000  16.000000  17.000000
D   18.0   19.0   20.0  21.000000  22.000000  23.000000

In [122]:
# 実行して表示
pd.concat([df1, df2], axis=1)

col_0  col_1  col_2      col_3      col_4      col_5  col_0  col_1  col_2   
P   34.0   35.0   78.0  50.466294  45.056174  52.707282    NaN    NaN    NaN  \
Q   45.0   35.0    9.0  54.438638  49.111752  40.588455    NaN    NaN    NaN   
R   24.0   26.0   12.0  42.889460  40.686044  54.397684    NaN    NaN    NaN   
S   29.0   33.0   13.0  42.714807  53.924057  59.241150    NaN    NaN    NaN   
A    NaN    NaN    NaN        NaN        NaN        NaN    0.0    1.0    2.0   
B    NaN    NaN    NaN        NaN        NaN        NaN    6.0    7.0    8.0   
C    NaN    NaN    NaN        NaN        NaN        NaN   12.0   13.0   14.0   
D    NaN    NaN    NaN        NaN        NaN        NaN   18.0   19.0   20.0   

   col_3  col_4  col_5  
P    NaN    NaN    NaN  
Q    NaN    NaN    NaN  
R    NaN    NaN    NaN  
S    NaN    NaN    NaN  
A    3.0    4.0    5.0  
B    9.0   10.0   11.0  
C   15.0   16.0   17.0  
D   21.0   22.0   23.0

Exercise_7: exercise_2のarr_intとarr_uniをnp.concatenateとは別のメソッドで縦方向、横方向に結合してください。

In [123]:
# 縦方向
arr_v = np.vstack([arr_int, arr_int])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr_v = np.vstack([arr_int, arr_uni])</code>
</details>

In [124]:
# 実行して表示
arr_v

array([[34, 35, 78],
       [45, 35,  9],
       [24, 26, 12],
       [29, 33, 13],
       [34, 35, 78],
       [45, 35,  9],
       [24, 26, 12],
       [29, 33, 13]])

In [125]:
# 横方向
arr_h = np.hstack([arr_int, arr_int])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr_h = np.hstack([arr_int, arr_uni])</code>
</details>

In [126]:
# 実行して表示
arr_h

array([[34, 35, 78, 34, 35, 78],
       [45, 35,  9, 45, 35,  9],
       [24, 26, 12, 24, 26, 12],
       [29, 33, 13, 29, 33, 13]])

Exercise_8 : df の index count, column, non-null count, dtype などのInformation一覧を表示してください

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, P to D
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col_0   8 non-null      float64
 1   col_1   8 non-null      float64
 2   col_2   8 non-null      float64
 3   col_3   8 non-null      float64
 4   col_4   8 non-null      float64
 5   col_5   8 non-null      float64
dtypes: float64(6)
memory usage: 448.0+ bytes


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.info()</code>
</details>

Exercise_9: dfの列毎の数値の合計、行毎の数値の合計を表示してください

In [128]:
# 列
df.sum(axis=0)

col_0    168.000000
col_1    169.000000
col_2    156.000000
col_3    238.509199
col_4    240.778028
col_5    262.934572
dtype: float64

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.sum()</code>
</details>

In [129]:
# 行
df.sum(axis=1)

P    295.229750
Q    233.138846
R    199.973188
S    230.880014
A     15.000000
B     51.000000
C     87.000000
D    123.000000
dtype: float64

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.sum(axis=1)</code>
</details>

Exercise_10: dfの先頭3行を表示してください。またdfをシャッフルし（df_shuffled）、その末尾の3行を表示してください。

In [130]:
# 先頭3行
df.head(3)

col_0  col_1  col_2      col_3      col_4      col_5
P   34.0   35.0   78.0  50.466294  45.056174  52.707282
Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
R   24.0   26.0   12.0  42.889460  40.686044  54.397684

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.head(3)</code>
</details>

In [131]:
df_shuffled = df.sample(frac=1)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df_shuffled = df.sample(frac=1)</code>
</details>

In [132]:
df_shuffled.tail(3)

col_0  col_1  col_2      col_3      col_4      col_5
Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
A    0.0    1.0    2.0   3.000000   4.000000   5.000000
S   29.0   33.0   13.0  42.714807  53.924057  59.241150

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df_shuffled.tail(3)</code>
</details>

Exercise_11 : df を 現在の index(A, B, ..., S) に対して降順に並べ替え（df.sort_index(inplace=True)）、index をリセットし0,1,2の通し番号に戻してくだださい。さらに新規にできるカラム'index' を 'class' に変更してください。

In [133]:
# 実行して表示
df

col_0  col_1  col_2      col_3      col_4      col_5
P   34.0   35.0   78.0  50.466294  45.056174  52.707282
Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
R   24.0   26.0   12.0  42.889460  40.686044  54.397684
S   29.0   33.0   13.0  42.714807  53.924057  59.241150
A    0.0    1.0    2.0   3.000000   4.000000   5.000000
B    6.0    7.0    8.0   9.000000  10.000000  11.000000
C   12.0   13.0   14.0  15.000000  16.000000  17.000000
D   18.0   19.0   20.0  21.000000  22.000000  23.000000

In [134]:
# 並べ替えのみ。（コース内での紹介はありませんでした）
df.sort_index(inplace=True)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.sort_index(inplace=True)</code>
</details>

In [135]:
# 実行して表示
df

col_0  col_1  col_2      col_3      col_4      col_5
A    0.0    1.0    2.0   3.000000   4.000000   5.000000
B    6.0    7.0    8.0   9.000000  10.000000  11.000000
C   12.0   13.0   14.0  15.000000  16.000000  17.000000
D   18.0   19.0   20.0  21.000000  22.000000  23.000000
P   34.0   35.0   78.0  50.466294  45.056174  52.707282
Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
R   24.0   26.0   12.0  42.889460  40.686044  54.397684
S   29.0   33.0   13.0  42.714807  53.924057  59.241150

In [136]:
# indexをリセット
df.reset_index(inplace=True)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.reset_index(inplace=True)</code>
</details>

In [137]:
# 実行して表示
df

index  col_0  col_1  col_2      col_3      col_4      col_5
0     A    0.0    1.0    2.0   3.000000   4.000000   5.000000
1     B    6.0    7.0    8.0   9.000000  10.000000  11.000000
2     C   12.0   13.0   14.0  15.000000  16.000000  17.000000
3     D   18.0   19.0   20.0  21.000000  22.000000  23.000000
4     P   34.0   35.0   78.0  50.466294  45.056174  52.707282
5     Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
6     R   24.0   26.0   12.0  42.889460  40.686044  54.397684
7     S   29.0   33.0   13.0  42.714807  53.924057  59.241150

In [138]:
# column名を変更
df.rename(columns={"index": "class"}, inplace=True)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.rename(columns={'index':'class'}, inplace=True)</code>
</details>

In [139]:
# 実行して表示
df

class  col_0  col_1  col_2      col_3      col_4      col_5
0     A    0.0    1.0    2.0   3.000000   4.000000   5.000000
1     B    6.0    7.0    8.0   9.000000  10.000000  11.000000
2     C   12.0   13.0   14.0  15.000000  16.000000  17.000000
3     D   18.0   19.0   20.0  21.000000  22.000000  23.000000
4     P   34.0   35.0   78.0  50.466294  45.056174  52.707282
5     Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
6     R   24.0   26.0   12.0  42.889460  40.686044  54.397684
7     S   29.0   33.0   13.0  42.714807  53.924057  59.241150

Exercise_12 : dfの各カラム名の末尾に'*'の文字列を付加したデータフレーム（df_star）を作成してください

In [141]:
df_star = df.add_suffix("*")

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df_star = df.add_suffix('*')</code>
</details>

In [142]:
# 実行して表示
df_star

class*  col_0*  col_1*  col_2*     col_3*     col_4*     col_5*
0      A     0.0     1.0     2.0   3.000000   4.000000   5.000000
1      B     6.0     7.0     8.0   9.000000  10.000000  11.000000
2      C    12.0    13.0    14.0  15.000000  16.000000  17.000000
3      D    18.0    19.0    20.0  21.000000  22.000000  23.000000
4      P    34.0    35.0    78.0  50.466294  45.056174  52.707282
5      Q    45.0    35.0     9.0  54.438638  49.111752  40.588455
6      R    24.0    26.0    12.0  42.889460  40.686044  54.397684
7      S    29.0    33.0    13.0  42.714807  53.924057  59.241150

Exercise_13 : dfのレコード（サンプル）ごとの値をリストとして取り出してください。また、レコードごとの{カラム名：値, .....｝形式のディクショナリ―も作成してください（リスト内のディクショナリー）

In [146]:
df.values.tolist()

[['A', 0.0, 1.0, 2.0, 3.0, 4.0, 5.0],
 ['B', 6.0, 7.0, 8.0, 9.0, 10.0, 11.0],
 ['C', 12.0, 13.0, 14.0, 15.0, 16.0, 17.0],
 ['D', 18.0, 19.0, 20.0, 21.0, 22.0, 23.0],
 ['P',
  34.0,
  35.0,
  78.0,
  50.46629377521173,
  45.05617439448399,
  52.70728211067636],
 ['Q',
  45.0,
  35.0,
  9.0,
  54.43863826057332,
  49.111752235197514,
  40.58845519814566],
 ['R',
  24.0,
  26.0,
  12.0,
  42.88945961413155,
  40.686044378859165,
  54.39768434878043],
 ['S',
  29.0,
  33.0,
  13.0,
  42.71480746041389,
  53.924056508113964,
  59.24115030881612]]

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.values.tolist()</code>
</details>

In [147]:
df.to_dict(orient="records")

[{'class': 'A',
  'col_0': 0.0,
  'col_1': 1.0,
  'col_2': 2.0,
  'col_3': 3.0,
  'col_4': 4.0,
  'col_5': 5.0},
 {'class': 'B',
  'col_0': 6.0,
  'col_1': 7.0,
  'col_2': 8.0,
  'col_3': 9.0,
  'col_4': 10.0,
  'col_5': 11.0},
 {'class': 'C',
  'col_0': 12.0,
  'col_1': 13.0,
  'col_2': 14.0,
  'col_3': 15.0,
  'col_4': 16.0,
  'col_5': 17.0},
 {'class': 'D',
  'col_0': 18.0,
  'col_1': 19.0,
  'col_2': 20.0,
  'col_3': 21.0,
  'col_4': 22.0,
  'col_5': 23.0},
 {'class': 'P',
  'col_0': 34.0,
  'col_1': 35.0,
  'col_2': 78.0,
  'col_3': 50.46629377521173,
  'col_4': 45.05617439448399,
  'col_5': 52.70728211067636},
 {'class': 'Q',
  'col_0': 45.0,
  'col_1': 35.0,
  'col_2': 9.0,
  'col_3': 54.43863826057332,
  'col_4': 49.111752235197514,
  'col_5': 40.58845519814566},
 {'class': 'R',
  'col_0': 24.0,
  'col_1': 26.0,
  'col_2': 12.0,
  'col_3': 42.88945961413155,
  'col_4': 40.686044378859165,
  'col_5': 54.39768434878043},
 {'class': 'S',
  'col_0': 29.0,
  'col_1': 33.0,
  'col_2'

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.to_dict(orient='records')</code>
</details>

Exercise_14 : 以下でいくつかの値を np.nan で置き換えています。DataFrame形式ですべての要素に対して nan であるかどうかをTrue/Falseで表示してください。またカラム毎の nan の合計、全体の nan の合計を表示してください。

In [148]:
# 実行して表示
list_null = [[0, 2], [2, 3], [3, 4], [4, 5], [6, 5]]
for i in list_null:
    df.iloc[i[0], i[1]] = np.nan

df

class  col_0  col_1  col_2      col_3      col_4      col_5
0     A    0.0    NaN    2.0   3.000000   4.000000   5.000000
1     B    6.0    7.0    8.0   9.000000  10.000000  11.000000
2     C   12.0   13.0    NaN  15.000000  16.000000  17.000000
3     D   18.0   19.0   20.0        NaN  22.000000  23.000000
4     P   34.0   35.0   78.0  50.466294        NaN  52.707282
5     Q   45.0   35.0    9.0  54.438638  49.111752  40.588455
6     R   24.0   26.0   12.0  42.889460        NaN  54.397684
7     S   29.0   33.0   13.0  42.714807  53.924057  59.241150

In [150]:
# すべての要素に対して True or False
df.isnull()

class  col_0  col_1  col_2  col_3  col_4  col_5
0  False  False   True  False  False  False  False
1  False  False  False  False  False  False  False
2  False  False  False   True  False  False  False
3  False  False  False  False   True  False  False
4  False  False  False  False  False   True  False
5  False  False  False  False  False  False  False
6  False  False  False  False  False   True  False
7  False  False  False  False  False  False  False

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.isnull()</code>
</details>

In [151]:
# カラム毎のnanの合計
df.isnull().sum()

class    0
col_0    0
col_1    1
col_2    1
col_3    1
col_4    2
col_5    0
dtype: int64

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.isnull().sum()</code>
</details>

In [152]:
# 全体のnanの合計
df.isnull().sum().sum()

5

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.isnull().sum().sum()</code>
</details>

Exercise_15 : nanではないレコードの数をカラム毎に表示して下さい

In [153]:
df.count()

class    8
col_0    8
col_1    7
col_2    7
col_3    7
col_4    6
col_5    8
dtype: int64

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.count()</code>
</details>

Exercise_14 : nan を含むレコードのみを表示して下さい。　ヒント：「各レコード」に対して nan の合計を求め、それが 1 以上のものだけを抽出

In [154]:
# レコード毎のnanの合計
df.isnull().sum(axis=1)

0    1
1    0
2    1
3    1
4    1
5    0
6    1
7    0
dtype: int64

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.isnull().sum(axis=1)</code>
</details>

In [158]:
# 上記の合計 >= 1 の条件で抽出
# .style.highlight_null(null_color='red')を使ってください
df[df.isnull().sum(axis=1) >= 1].style.highlight_null(color="red")

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df[df.isnull().sum(axis=1) >= 1].style.highlight_null(null_color='red')</code>
</details>

Exercise_16 : dfの数値のみのカラム毎の合計値を、異なる二つの手法で求めてください

In [159]:
# 実行して表示
df.sum()

class      ABCDPQRS
col_0         168.0
col_1         168.0
col_2         142.0
col_3    217.509199
col_4    155.035809
col_5    262.934572
dtype: object

In [160]:
# sumのキーワードアーギュメント（キーワード引数）を指定する方法
df.sum(numeric_only=True)

col_0    168.000000
col_1    168.000000
col_2    142.000000
col_3    217.509199
col_4    155.035809
col_5    262.934572
dtype: float64

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.sum(numeric_only=True)</code>
</details>

In [162]:
# dtypeが数値のもののみを選択する方法
df.select_dtypes(include=[int, float]).sum()

col_0    168.000000
col_1    168.000000
col_2    142.000000
col_3    217.509199
col_4    155.035809
col_5    262.934572
dtype: float64

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.select_dtypes(include=[int, float]).sum()</code>
</details>

Exercise_17 : nan を視覚的に把握できるように seaborn の heatmap で df.isnull() を表示してください。  

In [ ]:
# 実行して表示するだけ
sns.heatmap(df.isnull())

Exercise_18 : 今回作成した df を df_exercise.csv として現在のワーキングディレクトリに保存してください

In [163]:
df.to_csv("df_exercise.csv")

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.to_csv('df_exercise.csv')</code>
</details>

Exercise_19 : 下記の値を答えてください

In [164]:
# 実行して表示
np.random.seed(17)
arr = np.arange(12).reshape(2, 2, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [165]:
# 結果を考えてから、実行して確認
print(arr.sum(axis=0))

[[ 6  8 10]
 [12 14 16]]


In [166]:
# 結果を考えてから、実行して確認
print(arr.sum(axis=1))

[[ 3  5  7]
 [15 17 19]]


In [167]:
# 結果を考えてから、実行して確認
print(arr.mean(axis=2))

[[ 1.  4.]
 [ 7. 10.]]


## 以上