---
# 7.Categorical Features Exercise

---

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Exercise_1 : LabelEncoder、OneHotEncoderをインポートしてください

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>from sklearn.preprocessing import LabelEncoder</code><br>
    <code>from sklearn.preprocessing import OneHotEncoder</code><br>
</details>

Exercise_2:Seabornのデータセットから'diamonds'をデータフレームdfとして読み込んでください。その際に利用するカラムを['cut', 'color', 'clarity']としてください。　ヒント　usecolsを使う

In [4]:
df = sns.load_dataset(name="diamonds", usecols=["cut", "color", "clarity"])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df = sns.load_dataset('diamonds', usecols=['cut', 'color', 'clarity'])</code><br>
</details>

In [5]:
# 実行して表示
df.head()

cut color clarity
0    Ideal     E     SI2
1  Premium     E     SI1
2     Good     E     VS1
3  Premium     I     VS2
4     Good     J     SI2

In [6]:
# 実行して表示
df["clarity"].value_counts()

clarity
SI1     13065
VS2     12258
SI2      9194
VS1      8171
VVS2     5066
VVS1     3655
IF       1790
I1        741
Name: count, dtype: int64

Exercise_3 :'clarity'の各要素の文字列の最後の一文字を削除してください（SI1 => SI, VS2 => VSなど。練習用に分類数を少なくするために）。

In [7]:
df["clarity"] = df["clarity"].str[:-1]

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df['clality'] = df['clarity'].str[:-1]</code><br>
</details>

In [8]:
# 実行して表示
df["clarity"].value_counts()

clarity
SI     22259
VS     20429
VVS     8721
I       2531
Name: count, dtype: int64

Exercise_4 :'color'も分類が多いため、'D', 'E', 'F', 'G'の値を np.nan に置換してください。（練習用に分類数を少なくするために）。　ヒント　.loc, .isinを利用

In [9]:
df.loc[df["color"].isin(list("DEFG")), "color"] = np.nan

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.loc[df['color'].isin(list('DEFG')), 'color' ] = np.nan</code><br>
</details>

In [10]:
# 実行して表示
df["color"].value_counts()

color
H    8304
I    5422
J    2808
D       0
E       0
F       0
G       0
Name: count, dtype: int64

Exercise_5 :上記で'D', 'E', 'F', 'G'が value として残っている原因はデータタイプにあります。データタイプを確認して、'D', 'E', 'F', 'G'のカラムを削除してください。

In [11]:
# データタイプを確認してください
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   cut      53940 non-null  category
 1   color    16534 non-null  category
 2   clarity  53940 non-null  object  
dtypes: category(2), object(1)
memory usage: 527.4+ KB


<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df.info()</code><br>
</details>

In [12]:
# 'cut', 'color'のデータタイプを変更してください
df["cut"] = df["cut"].astype(object)
df["color"] = df["color"].astype(object)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df['cut'] = df['cut'].astype(object)</code><br>
    <code>df['color'] = df['color'].astype(object)</code><br>
</details>

In [13]:
# 実行して表示。データタイプが変更されていることを確認
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   cut      53940 non-null  object
 1   color    16534 non-null  object
 2   clarity  53940 non-null  object
dtypes: object(3)
memory usage: 1.2+ MB


In [14]:
# 実行してください
# 他のカラムにも np.nan を配置しておきます。'I', 'Fair'を選択したことに特別な意味はありません。
df.loc[df["clarity"] == "I", "clarity"] = np.nan
df.loc[df["cut"] == "Fair", "cut"] = np.nan

In [15]:
# 実行して表示
df.head()

cut color clarity
0    Ideal   NaN      SI
1  Premium   NaN      SI
2     Good   NaN      VS
3  Premium     I      VS
4     Good     J      SI

Exercise_6 :LabelEncoderを使って'cut'カラムを数値ラベルに変換してください

In [16]:
# インスタンスの作成
label_encoder = LabelEncoder()

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>label_encoder = LabelEncoder()</code><br>
</details>

In [18]:
# フィット
label_encoder.fit(df["cut"])

LabelEncoder()

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>label_encoder.fit(df['cut'])</code><br>
</details>

In [19]:
# 変換したデータを新しいカラム'class'に代入
df["class"] = label_encoder.transform(df["cut"])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df['class'] = label_encoder.transform(df['cut'])</code><br>
</details>

In [20]:
# 実行して表示
df.head()

cut color clarity  class
0    Ideal   NaN      SI      1
1  Premium   NaN      SI      2
2     Good   NaN      VS      0
3  Premium     I      VS      2
4     Good     J      SI      0

Exercise_7 :label_encoderが学習し、記憶しているクラス('Good', 'Very Good'など)の一覧を表示してください

In [21]:
# アルファベット順になることに注意してください。
label_encoder.classes_

array(['Good', 'Ideal', 'Premium', 'Very Good', nan], dtype=object)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>label_encoder.classes_</code><br>
</details>

Exercise_8 :label_encoderで[0, 2, 4]を逆変換し、その結果を表示してください

In [23]:
label_encoder.inverse_transform([0, 2, 4])

array(['Good', 'Premium', nan], dtype=object)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>label_encoder.inverse_transform([0, 2, 4])</code><br>
</details>

Exercise_9 :Pandasのget_dummies()を用いて np.nan であることも分かるようにカラム'color'をダミー変数化し、df_cdを作成してください

In [24]:
pd.get_dummies(df, columns=["color"], dummy_na=True)df_cd =  

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df_cd = pd.get_dummies(df, columns=['color'], dummy_na=True)</code><br>
</details>

In [25]:
# 実行して表示
df_cd.head()

cut clarity  class  color_H  color_I  color_J  color_nan
0    Ideal      SI      1    False    False    False       True
1  Premium      SI      2    False    False    False       True
2     Good      VS      0    False    False    False       True
3  Premium      VS      2    False     True    False      False
4     Good      SI      0    False    False     True      False

Exercise_10 :同様にPandasのget_dummies()を用いて np.nan であることも分かるようにカラム'color'をダミー変数化しますが、その際に先頭の'color_H'は余分な情報となっていますので、それを削除してdfを上書きしてください

In [26]:
df = pd.get_dummies(df, columns=["color"], dummy_na=True, drop_first=True)

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df = pd.get_dummies(df, columns=['color'], dummy_na=True, drop_first=True))</code><br>
</details>

In [27]:
# 実行して表示
df.head()

cut clarity  class  color_I  color_J  color_nan
0    Ideal      SI      1    False    False       True
1  Premium      SI      2    False    False       True
2     Good      VS      0    False    False       True
3  Premium      VS      2     True    False      False
4     Good      SI      0    False     True      False

Exercise_11 :現在のdfから'color'が'H'であるレコード（I, J, nanがすべて0）を抽出し、先頭5行を表示してください（'H'が確かに区別されることを確認するため）

In [33]:
# 様々な方法があります。解答は一例です
df[(df["color_I"] == df["color_J"]) & (df["color_J"] == df["color_nan"])].head()

# 7, 9, 22, 37, 44ならばOK

cut clarity  class  color_I  color_J  color_nan
7   Very Good      SI      3    False    False      False
9   Very Good      VS      3    False    False      False
22  Very Good      VS      3    False    False      False
37       Good      SI      0    False    False      False
44       Good      SI      0    False    False      False

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>df[df.iloc[:, 3:6].sum(axis=1) == 0].head()</code><br>
</details>

In [34]:
# 実行して表示。handle_unknownの使用方法を確認するために以下で新規のDataFrameを作成します
df.iloc[5:15, :2]

cut clarity
5   Very Good     VVS
6   Very Good     VVS
7   Very Good      SI
8         NaN      VS
9   Very Good      VS
10       Good      SI
11      Ideal      VS
12    Premium      SI
13      Ideal      SI
14    Premium      SI

In [35]:
# 実行して表示
# df_train, df_testを新規作成します
df_train = df.iloc[5:12, :2]
df_test = df.iloc[12:16, :2]
df_train

cut clarity
5   Very Good     VVS
6   Very Good     VVS
7   Very Good      SI
8         NaN      VS
9   Very Good      VS
10       Good      SI
11      Ideal      VS

In [36]:
# 実行して表示
df_test
# df_testの'cut'にはdf_trainには存在しない'Premium'が含まれており、
# 同様に'clarity'にはNaNが含まれています

cut clarity
12  Premium      SI
13    Ideal      SI
14  Premium      SI
15  Premium     NaN

Exercise_12 :OneHotEncoderを用いてdf_trainをダミー変数化してください。

In [37]:
# インスタンス作成
onehot_encoder = OneHotEncoder()

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>onehot_encoder = OneHotEncoder()</code><br>
</details>

In [38]:
# トレインデータのフィットと変換を同時に実行
onehot_encoder.fit_transform(df_train)

<7x7 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>onehot_encoder.fit_transform(df_train)</code><br>
</details>

In [39]:
# アレイに変換
arr_train = onehot_encoder.fit_transform(df_train).toarray()
arr_train
# 'cut'に4列、'clarity'に3列

array([[0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0.]])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr = onehot_encoder.fit_transform(df_train).toarray()</code><br>
</details>

Exercise_13 :arr のそれぞれの列が表すカテゴリを確認してください

In [40]:
# 実行して表示
arr_train.shape

(7, 7)

In [41]:
# カテゴリー名を表示してください
onehot_encoder.categories_

[array(['Good', 'Ideal', 'Very Good', nan], dtype=object),
 array(['SI', 'VS', 'VVS'], dtype=object)]

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>onehot_encoder.categories_</code><br>
</details>

Exercise_14 :同様の操作を drop='first' を設定して行ってください

In [50]:
# インスタンス作成
onehot_encoder_drop = OneHotEncoder(drop="first")

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>onehot_encoder_drop = OneHotEncoder(drop='first') </code><br>
</details>

In [51]:
# トレインデータのフィットと変換
onehot_encoder_drop.fit_transform(df_train)

<7x5 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>onehot_encoder_drop.fit_transform(df_train)</code><br>
</details>

In [52]:
# アレイに変換
arr_train_drop = onehot_encoder_drop.fit_transform(df_train).toarray()
arr_train_drop

array([[0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 1., 0.]])

<details>
    <summary><font color='red'>解答はここをクリック</font></summary>
    <code>arr_train_drop = onehot_encoder_drop.fit_transform(df_train).toarray()</code><br>
</details>

In [53]:
# 実行して表示
arr_train_drop.shape

(7, 5)

In [54]:
# 実行して表示。上記で列数が 5 に変化していますが全カテゴリが記憶されています
onehot_encoder_drop.categories_
# ドロップされたカテゴリはそれぞれの先頭の'Good'と'SI'です

[array(['Good', 'Ideal', 'Very Good', nan], dtype=object),
 array(['SI', 'VS', 'VVS'], dtype=object)]

Exercise_15 :onehot_encoder_dropを用いてdf_testを変換してください。df_trainにはない'Premium'が存在するため、ERRORが発生します。

In [55]:
arr_test = onehot_encoder_drop.transform(df_test).toarray()
arr_test
# ValueError: Found unknown categories ['Premium'] in column 0 during transform

ValueError: Found unknown categories ['Premium'] in column 0 during transform

In [56]:
# 実行して表示。パラメーター'handle_unknown'はデフェルトで'error'に設定されています
onehot_encoder_drop.handle_unknown

'error'

Exercise_16 :handle_unknownに'ignore'を設定し、あらためてdf_trainにおいてfitを行ってください

In [60]:
# インスタンス作成
onehot_encoder = OneHotEncoder(handle_unknown="ignore")

In [61]:
# fit
onehot_encoder.fit(df_train)

OneHotEncoder(handle_unknown='ignore')

Exercise_17:上記onehot_encoderでdf_testを変換し、ERRORが発生しないこととunknownである'Premium'がすべて 0 として表現されていることを確認してください

In [62]:
# 変換してアレイに
arr_test = onehot_encoder.transform(df_test).toarray()
arr_test
# 先頭の四つが'cut'を表す。すべて0はCategoriesにない未知の値

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## 以上